name: fasttext_predict
version: 0.0.1
description: >-
  Call Fasttext predict from Dart
# This example isn't intended for publishing on pub.dev.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  ffi: ^2.0.1
